[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"