[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"

[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://ofix-backend-prod.onrender.com"