import { useState, useEffect } from 'react';
import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogDescription,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import * as servicosService from '../../services/servicos.service.js';
import { Save, Plus, Hash, RefreshCw } from "lucide-react";
import toast from 'react-hot-toast';

// Função para gerar número automático da OS
const generateOSNumber = () => {
    const now = new Date();
    const year = now.getFullYear();
    const month = String(now.getMonth() + 1).padStart(2, '0');
    const day = String(now.getDate()).padStart(2, '0');
    const hour = String(now.getHours()).padStart(2, '0');
    const minute = String(now.getMinutes()).padStart(2, '0');
    const second = String(now.getSeconds()).padStart(2, '0');
    
    // Adiciona um número aleatório para garantir unicidade
    const random = String(Math.floor(Math.random() * 100)).padStart(2, '0');
    
    return `OS-${year}${month}${day}-${hour}${minute}${second}-${random}`;
};

// Objeto com os dados iniciais do formulário. Definido fora do componente.
const initialFormData = {
    numeroOs: '',
    clienteId: '',
    veiculoId: '',
    descricaoProblema: '',
    dataEntrada: new Date().toISOString().split('T')[0],
    kmEntrada: '',
    valorTotalEstimado: '',
};

export default function NewServiceModal({ isOpen, onClose, onSuccess: reloadDashboard, clientes, veiculos }) {
    
    // CORREÇÃO: Inicializa o estado com a constante definida acima.
    const [formData, setFormData] = useState(initialFormData);
    const [isCreating, setIsCreating] = useState(false);
    const [isAutoGenerated, setIsAutoGenerated] = useState(false);

    // Gera automaticamente o número da OS quando o modal abre
    useEffect(() => {
        if (isOpen && !formData.numeroOs) {
            const autoNumber = generateOSNumber();
            setFormData(prev => ({ ...prev, numeroOs: autoNumber }));
            setIsAutoGenerated(true);
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [isOpen]);

    // Função para gerar novo número da OS
    const handleGenerateNewNumber = () => {
        const newNumber = generateOSNumber();
        
        setFormData(prev => ({ ...prev, numeroOs: newNumber }));
        setIsAutoGenerated(true);
        toast.success(`Novo número gerado: ${newNumber}`);
    };

    // FUNÇÃO FALTANTE: Lida com a mudança de valores nos inputs.
    const handleChange = (e) => {
        const { id, value } = e.target;
        setFormData(prevData => ({
            ...prevData,
            [id]: value,
        }));
        
        // Se o usuário editar manualmente o número da OS, marca como não auto-gerado
        if (id === 'numeroOs') {
            setIsAutoGenerated(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        
        if (!formData.numeroOs || !formData.clienteId || !formData.veiculoId) {
            toast.error("Preencha os campos obrigatórios: Número da OS, Cliente e Veículo.");
            return;
        }

        setIsCreating(true);
        const toastId = toast.loading("Criando nova ordem de serviço...");

        try {
            const dataToSend = {
                ...formData,
                // Converte campos que devem ser numéricos antes de enviar
                kmEntrada: formData.kmEntrada ? parseInt(formData.kmEntrada, 10) : null,
                valorTotalEstimado: formData.valorTotalEstimado ? parseFloat(formData.valorTotalEstimado) : null,
            };

            await servicosService.createServico(dataToSend);
            toast.success("Ordem de Serviço criada com sucesso!", { id: toastId });
            
            // Reseta o formulário e gera novo número para próxima OS
            const newFormData = { ...initialFormData, numeroOs: generateOSNumber() };
            setFormData(newFormData);
            setIsAutoGenerated(true);
            reloadDashboard(); // Recarrega os dados do dashboard
            onClose(); // Fecha o modal
        } catch (error) {
            const errorMessage = error.response?.data?.message || error.message || "Falha ao criar Ordem de Serviço.";
            toast.error(errorMessage, { id: toastId });
        } finally {
            setIsCreating(false);
        }
    };

    // A lógica para filtrar as opções continua ótima.
    const clienteOptions = Object.values(clientes || {});
    const veiculoOptions = formData.clienteId
        ? (veiculos || []).filter(v => v.clienteId === formData.clienteId)
        : [];

    return (
        <Dialog open={isOpen} onOpenChange={onClose}>
            <DialogContent className="bg-white text-black dark:bg-white dark:text-black p-6 rounded-xl shadow-xl max-w-3xl" aria-describedby="new-service-modal-description">
                <DialogHeader>
                    <DialogTitle className="text-2xl font-bold text-slate-900 flex items-center gap-2">
                        <Plus className="w-6 h-6" />
                        Nova Ordem de Serviço
                    </DialogTitle>
                    <DialogDescription>
                        Criar uma nova ordem de serviço com número gerado automaticamente
                    </DialogDescription>
                </DialogHeader>

                <form onSubmit={handleSubmit} className="space-y-6 pt-4">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label htmlFor="numeroOs" className="flex items-center gap-2">
                                <Hash className="w-4 h-4" />
                                Número da OS *
                                {isAutoGenerated && (
                                    <span className="text-xs text-green-600 font-medium px-2 py-1 bg-green-50 rounded-full">
                                        Gerado automaticamente
                                    </span>
                                )}
                            </Label>
                            <div className="flex gap-2">
                                <Input
                                    id="numeroOs"
                                    value={formData.numeroOs}
                                    onChange={handleChange}
                                    placeholder="Ex: OS-20250107-143025-45"
                                    className={isAutoGenerated ? "border-green-300 bg-green-50/50" : ""}
                                    required
                                />
                                <Button
                                    type="button"
                                    variant="outline"
                                    size="icon"
                                    onClick={handleGenerateNewNumber}
                                    title="Gerar novo número automático"
                                    className="shrink-0 hover:bg-blue-50 hover:border-blue-300"
                                >
                                    <RefreshCw className="w-4 h-4" />
                                </Button>
                            </div>
                            <p className="text-xs text-slate-500 mt-1">
                                Formato: OS-AAAAMMDD-HHMMSS-XX (gerado automaticamente)
                            </p>
                        </div>

                        <div>
                            <Label htmlFor="dataEntrada">Data de Entrada</Label>
                            <Input
                                id="dataEntrada"
                                type="date"
                                value={formData.dataEntrada}
                                onChange={handleChange}
                            />
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label htmlFor="clienteId">Cliente *</Label>
                            <Select
                                value={formData.clienteId}
                                onValueChange={(value) => setFormData({ ...formData, clienteId: value, veiculoId: '' })}
                                required
                            >
                                <SelectTrigger>
                                    <SelectValue placeholder="Selecione o cliente" />
                                </SelectTrigger>
                                <SelectContent>
                                    {clienteOptions.map((cliente) => (
                                        <SelectItem key={cliente.id} value={cliente.id.toString()}>
                                            {cliente.nomeCompleto}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>

                        <div>
                            <Label htmlFor="veiculoId">Veículo *</Label>
                            <Select
                                value={formData.veiculoId}
                                onValueChange={(value) => setFormData({ ...formData, veiculoId: value })}
                                disabled={!formData.clienteId || veiculoOptions.length === 0}
                                required
                            >
                                <SelectTrigger>
                                    <SelectValue placeholder={!formData.clienteId ? "Selecione um cliente primeiro" : "Selecione o veículo"} />
                                </SelectTrigger>
                                <SelectContent>
                                    {veiculoOptions.map((veiculo) => (
                                        <SelectItem key={veiculo.id} value={veiculo.id.toString()}>
                                            {veiculo.marca} {veiculo.modelo} - {veiculo.placa}
                                        </SelectItem>
                                    ))}
                                </SelectContent>
                            </Select>
                        </div>
                    </div>

                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div>
                            <Label htmlFor="kmEntrada">KM de Entrada</Label>
                            <Input id="kmEntrada" type="number" value={formData.kmEntrada} onChange={handleChange} />
                        </div>
                        <div>
                            <Label htmlFor="valorTotalEstimado">Valor Estimado (R$)</Label>
                            <Input id="valorTotalEstimado" type="number" step="0.01" value={formData.valorTotalEstimado} onChange={handleChange} placeholder="0.00"/>
                        </div>
                    </div>

                    <div>
                        <Label htmlFor="descricaoProblema">Descrição do Problema</Label>
                        <Textarea
                            id="descricaoProblema"
                            value={formData.descricaoProblema}
                            onChange={handleChange}
                            placeholder="Descreva o problema relatado pelo cliente..."
                            className="h-24"
                        />
                    </div>

                    <div className="flex justify-end gap-3 pt-4">
                        <Button type="button" variant="outline" onClick={onClose}>
                            Cancelar
                        </Button>
                        <Button
                            type="submit"
                            disabled={isCreating}
                            className="bg-green-600 hover:bg-green-700"
                        >
                            <Save className="w-4 h-4 mr-2" />
                            {isCreating ? 'Criando...' : 'Criar Ordem de Serviço'}
                        </Button>
                    </div>
                </form>
            </DialogContent>
        </Dialog>
    );
}